### ISSUE TITLE
Update Sidebar component

### ISSUE THREAD

**Issue by jefferymills** [trelliscope/trelliscopejs-lib#101]
### Tasks
- [x] Folderize
- [ ] Create unit tests
- [x] Convert to CSS Modules
- [x] Convert to functional component
- [x] Add PropTypes and Default Props
- [ ] Convert to Typescript
