### ISSUE TITLE
Update HeaderLogo component

### ISSUE THREAD

**Issue by jefferymills** [trelliscope/trelliscopejs-lib#55]
### Tasks
- [x] Folderize
- [x] Create unit tests
- [x] Convert to CSS Modules
- [x] Convert to functional component
- [x] Add PropTypes and Default Props
- [x] Convert to Typescript
