### ISSUE TITLE
Update ExportInputDialog component

### ISSUE THREAD

**Issue by jefferymills** [trelliscope/trelliscopejs-lib#60]
### Tasks
- [x] Folderize
- [ ] Create unit tests
- [x] Convert to CSS Modules
- [x] Convert to functional component
- [x] Add PropTypes and Default Props
- [x] Convert to Typescript
