### ISSUE TITLE
Update FullscreenButton component

### ISSUE THREAD

**Issue by jefferymills** [trelliscope/trelliscopejs-lib#64]
### Tasks
- [x] Folderize
- [ ] Create unit tests
- [ ] Convert to CSS Modules
- [ ] Convert to functional component
- [ ] Add PropTypes and Default Props
- [ ] Convert to Typescript
