### ISSUE TITLE
Update Panel component

### ISSUE THREAD

**Issue by jefferymills** [trelliscope/trelliscopejs-lib#67]
### Tasks
- [x] Folderize
- [x] Convert to CSS Modules
- [x] Convert to functional component
- [x] Add Default Props
- [x] Convert to Typescript
