### ISSUE TITLE
Update SidebarLabels component

### ISSUE THREAD

**Issue by jefferymills** [trelliscope/trelliscopejs-lib#68]
### Tasks
- [x] Folderize
- [ ] Create unit tests
- [x] Convert to CSS Modules
- [x] Convert to functional component
- [ ] Add PropTypes and Default Props
- [x] Convert to Typescript
