### ISSUE TITLE
Update SidebarViews component

### ISSUE THREAD

**Issue by jefferymills** [trelliscope/trelliscopejs-lib#70]
### Tasks
- [ ] Folderize
- [ ] Create unit tests
- [ ] Convert to CSS Modules
- [ ] Convert to functional component
- [ ] Add PropTypes and Default Props
- [ ] Convert to Typescript
