### ISSUE TITLE
Update SideButton component

### ISSUE THREAD

**Issue by jefferymills** [trelliscope/trelliscopejs-lib#71]
### Tasks
- [x] Folderize
- [x] Convert to CSS Modules
- [x] Convert to functional component
- [x] Add Default Props
- [x] Convert to Typescript
