### ISSUE TITLE
Update App component

### ISSUE THREAD

**Issue by jefferymills** [trelliscope/trelliscopejs-lib#91]
### Tasks
- [ ] Folderize
- [ ] Create unit tests
- [ ] Convert to CSS Modules
- [ ] Convert to functional component
- [ ] Add PropTypes and Default Props
- [x] Convert to Typescript
